Hash to g2
Concordium/concordium-base pull request #21
Opened 2021-04-22 15:20 UTC by SimonKamp

## Purpose

Allow us to hash to the G2 subgroup of BLS12-381 for key generation.

## Changes

Adds an implementation of hash_to_curve suite BLS12381G2_XMD:SHA-256_SSWU_RO_ defined in https://tools.ietf.org/html/draft-irtf-cfrg-hash-to-curve-10#section-8.8.2

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

2021-04-22 15:59 UTC, abizjak requested changes

2021-04-22 15:59 UTC, abizjak commented on rust-src/curve_arithmetic/src/bls12_381_instance.rs
> +    fn hash_to_group(b: &[u8]) -> Self { hash_to_curve_g2(b, HASH_TO_GROUP_G1_DST).into_affine() }
```suggestion
    fn hash_to_group(b: &[u8]) -> Self { hash_to_curve_g2(b, HASH_TO_GROUP_G2_DST).into_affine() }
```

I think this looks like a copy-paste error.

2021-04-26 10:51 UTC, eb-concordium approved these changes

2021-04-26 11:34 UTC, eb-concordium approved these changes

2021-04-26 11:47 UTC, abizjak approved these changes

2021-04-26 11:47 UTC, merged