Merge Concordium Contracts Common
Concordium/concordium-base pull request #442
Opened 2023-09-13 08:12 UTC by Bargsteen

## Purpose

Merge Concordium Contracts Common(CCC) into base.

Currently, the only place CCC is used as a submodule on its own is in the rust-smart-contracts repo. But soon we will move the integration testing library from the contract-tools repo to rust-smart-contracts. At that point, no repositories depend on contracts common in isolation. Thus the merge.

## Changes

- Merge in the repo with its full history to the folder `smart-contracts/contracts-common` (the subfolders still have a `concordium-` prefix)
- Merge the Github workflow actions

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2023-09-13 14:18 UTC, limemloh approved these changes
LGTM assuming everything builds

2023-09-13 14:18 UTC, limemloh commented on smart-contracts/contracts-common/README.md
> +(the exact version used by the CI can be found in [.github/workflows/linter.yml](.github/workflows/linter.yml) file).
Link needs to be fixed, but maybe better is to remove this section since base have it already

2023-09-13 14:18 UTC, limemloh commented on smart-contracts/contracts-common/concordium-contracts-common/Cargo.toml
> +repository = "https://github.com/Concordium/concordium-contracts-common"
Needs to be updated

2023-09-13 20:02 UTC, abizjak approved these changes
Looks good, but please make a separate workflow.yml for checking contracts-common so we can only run it when it has changed.

2023-09-13 20:11 UTC, abizjak requested changes
Actually I now looked at the commits and if I understand correctly you had one massive commit renaming files to put them under contracts-common. This is less than ideal since git blame becomes harder, and we lose tags.

It would be better to use git filter-repo to just move everything and rewrite history that way.
We should ideally also copy over the release tags we used, and then also push those tags.

I think git-filter-repo should make this relatively easy and this is what we've done before.

https://github.com/newren/git-filter-repo#solving-this-with-filter-repo

2023-09-14 09:16 UTC, Bargsteen commented
> Actually I now looked at the commits and if I understand correctly you had one massive commit renaming files to put them under contracts-common. This is less than ideal since git blame becomes harder, and we lose tags.
> 
> It would be better to use git filter-repo to just move everything and rewrite history that way. We should ideally also copy over the release tags we used, and then also push those tags.
> 
> I think git-filter-repo should make this relatively easy and this is what we've done before.
> 
> https://github.com/newren/git-filter-repo#solving-this-with-filter-repo

Ah, I didn't notice that you could see it on the files. Thanks. I've created https://github.com/Concordium/concordium-base/pull/443 instead, in which I've used filter-repo and pushed the tags.

2023-09-14 09:16 UTC, closed without merging